name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: demo 
      - run: cd C:\Users\VanThuan\Desktop\WebBanHangBasic\WebBanHangBasic
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag demo:v${{ github.run_number }}
      - name: Copy new env file
        run: cd /home/app && cp origin.env .env
      - name: Pass new version
        run: cd /home/app && sh script.exe DEMO_VERSION ${{ github.run_number }} .env
      - name: Remove old version
        run: cd /home/app && docker compose rm demo
      - name: Up new version
        run: cd /home/app && docker compose up -d demo
